export const brands: string[] = [
    // Luxury & High-End Fashion Brands
    "Louis Vuitton",
    "Gucci",
    "Prada",
    "Chanel",
    "Hermès",
    "Dior",
    "Balenciaga",
    "Versace",
    "Burberry",
    "Fendi",
    "Valentino",
    "Givenchy",
    "Yves Saint Laurent",
    "Alexander McQueen",
    "Bottega Veneta",
    "Giorgio Armani",
    "Tom Ford",
    "Celine",
    "Dolce & Gabbana",
    "Maison Margiela",
    
    // Premium & Contemporary Brands
    "Off-White",
    "Jacquemus",
    "A.P.C.",
    "Isabel Marant",
    "Acne Studios",
    "Palm Angels",
    "The Row",
    "Zimmermann",
    "Moncler",
    "Rick Owens",
    
    // Streetwear & Urban Fashion Brands
    "Supreme",
    "Fear of God",
    "Stüssy",
    "BAPE",
    "Kith",
    "Vetements",
    "Stone Island",
    "Nike",
    "Adidas Originals",
    "Yeezy",
    
    // Mass-Market & Affordable Luxury
    "Zara",
    "H&M",
    "Uniqlo",
    "COS",
    "Massimo Dutti",
    "Mango",
    "ASOS",
    "Ted Baker",
    "Reiss",
    "Lululemon Athletica"
  ];
  